### ISSUE TITLE
LetrasCIF falta la U

### ISSUE THREAD

**Issue by Donchurru** [agarimo/Validador#1]
https://github.com/agarimo/Validador/blob/45d211d20e2789085eaf52be7b4bf13aa0244e64/src/principal/CalculaNif.java#L10

En las letras del CIF hay que añadirle la U, que también está entre las posibles

**Comment by agarimo** [comment]
Aqui tienes la misma clase más moderna que ya no contenía ese error, sin embargo gracias por la información.
https://github.com/agarimo/Util/blob/3.0/src/tools/CalculaNif.java
