### ISSUE TITLE
Faltan valores en cifLetra

### ISSUE THREAD

**Issue by Donchurru** [agarimo/Validador#2]
https://github.com/agarimo/Validador/blob/45d211d20e2789085eaf52be7b4bf13aa0244e64/src/principal/CalculaNif.java#L14

En esta lista de letras deberían ser "KPQRSNW" ya que han entrado nuevas en vigor:

http://www.jagar.es/Economia/Ccif.htm

**Comment by agarimo** [comment]
Problema solucionado, gracias por la información.

Aquí tienes una clase más moderna (en la que también se ha corregido el fallo) de cálculo de CIF
https://github.com/agarimo/Util/blob/3.0/src/tools/CalculaNif.java
